// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actionState.proto
package version2.proto.object;
public final class ActionStateProto {
  private ActionStateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ActionStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ActionState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required fixed64 start_time = 1;</code>
     * @return Whether the startTime field is set.
     */
    boolean hasStartTime();
    /**
     * <code>required fixed64 start_time = 1;</code>
     * @return The startTime.
     */
    long getStartTime();

    /**
     * <code>required fixed64 last_pkt_time = 2;</code>
     * @return Whether the lastPktTime field is set.
     */
    boolean hasLastPktTime();
    /**
     * <code>required fixed64 last_pkt_time = 2;</code>
     * @return The lastPktTime.
     */
    long getLastPktTime();

    /**
     * <code>required fixed64 cxid = 3;</code>
     * @return Whether the cxid field is set.
     */
    boolean hasCxid();
    /**
     * <code>required fixed64 cxid = 3;</code>
     * @return The cxid.
     */
    long getCxid();

    /**
     * <code>required uint32 reversed = 4;</code>
     * @return Whether the reversed field is set.
     */
    boolean hasReversed();
    /**
     * <code>required uint32 reversed = 4;</code>
     * @return The reversed.
     */
    int getReversed();

    /**
     * <code>required fixed32 af = 5;</code>
     * @return Whether the af field is set.
     */
    boolean hasAf();
    /**
     * <code>required fixed32 af = 5;</code>
     * @return The af.
     */
    int getAf();

    /**
     * <code>required fixed32 hw_proto = 6;</code>
     * @return Whether the hwProto field is set.
     */
    boolean hasHwProto();
    /**
     * <code>required fixed32 hw_proto = 6;</code>
     * @return The hwProto.
     */
    int getHwProto();

    /**
     * <code>required uint32 proto = 7;</code>
     * @return Whether the proto field is set.
     */
    boolean hasProto();
    /**
     * <code>required uint32 proto = 7;</code>
     * @return The proto.
     */
    int getProto();

    /**
     * <code>required fixed64 s_total_pkts = 8;</code>
     * @return Whether the sTotalPkts field is set.
     */
    boolean hasSTotalPkts();
    /**
     * <code>required fixed64 s_total_pkts = 8;</code>
     * @return The sTotalPkts.
     */
    long getSTotalPkts();

    /**
     * <code>required fixed64 s_total_bytes = 9;</code>
     * @return Whether the sTotalBytes field is set.
     */
    boolean hasSTotalBytes();
    /**
     * <code>required fixed64 s_total_bytes = 9;</code>
     * @return The sTotalBytes.
     */
    long getSTotalBytes();

    /**
     * <code>required fixed64 d_total_pkts = 10;</code>
     * @return Whether the dTotalPkts field is set.
     */
    boolean hasDTotalPkts();
    /**
     * <code>required fixed64 d_total_pkts = 10;</code>
     * @return The dTotalPkts.
     */
    long getDTotalPkts();

    /**
     * <code>required fixed64 d_total_bytes = 11;</code>
     * @return Whether the dTotalBytes field is set.
     */
    boolean hasDTotalBytes();
    /**
     * <code>required fixed64 d_total_bytes = 11;</code>
     * @return The dTotalBytes.
     */
    long getDTotalBytes();

    /**
     * <code>required uint32 s_tcpFlags = 12;</code>
     * @return Whether the sTcpFlags field is set.
     */
    boolean hasSTcpFlags();
    /**
     * <code>required uint32 s_tcpFlags = 12;</code>
     * @return The sTcpFlags.
     */
    int getSTcpFlags();

    /**
     * <code>required uint32 pad = 13;</code>
     * @return Whether the pad field is set.
     */
    boolean hasPad();
    /**
     * <code>required uint32 pad = 13;</code>
     * @return The pad.
     */
    int getPad();

    /**
     * <code>required uint32 d_tcpFlags = 14;</code>
     * @return Whether the dTcpFlags field is set.
     */
    boolean hasDTcpFlags();
    /**
     * <code>required uint32 d_tcpFlags = 14;</code>
     * @return The dTcpFlags.
     */
    int getDTcpFlags();

    /**
     * <code>required uint32 check = 15;</code>
     * @return Whether the check field is set.
     */
    boolean hasCheck();
    /**
     * <code>required uint32 check = 15;</code>
     * @return The check.
     */
    int getCheck();

    /**
     * <code>required fixed32 hash = 16;</code>
     * @return Whether the hash field is set.
     */
    boolean hasHash();
    /**
     * <code>required fixed32 hash = 16;</code>
     * @return The hash.
     */
    int getHash();
  }
  /**
   * Protobuf type {@code ActionState}
   */
  public static final class ActionState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ActionState)
      ActionStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActionState.newBuilder() to construct.
    private ActionState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActionState() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ActionState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActionState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              bitField0_ |= 0x00000001;
              startTime_ = input.readFixed64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              lastPktTime_ = input.readFixed64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              cxid_ = input.readFixed64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              reversed_ = input.readUInt32();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              af_ = input.readFixed32();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              hwProto_ = input.readFixed32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              proto_ = input.readUInt32();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              sTotalPkts_ = input.readFixed64();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              sTotalBytes_ = input.readFixed64();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000200;
              dTotalPkts_ = input.readFixed64();
              break;
            }
            case 89: {
              bitField0_ |= 0x00000400;
              dTotalBytes_ = input.readFixed64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              sTcpFlags_ = input.readUInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              pad_ = input.readUInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              dTcpFlags_ = input.readUInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              check_ = input.readUInt32();
              break;
            }
            case 133: {
              bitField0_ |= 0x00008000;
              hash_ = input.readFixed32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ActionStateProto.internal_static_ActionState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ActionStateProto.internal_static_ActionState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ActionStateProto.ActionState.class, ActionStateProto.ActionState.Builder.class);
    }

    private int bitField0_;
    public static final int START_TIME_FIELD_NUMBER = 1;
    private long startTime_;
    /**
     * <code>required fixed64 start_time = 1;</code>
     * @return Whether the startTime field is set.
     */
    @java.lang.Override
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required fixed64 start_time = 1;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }

    public static final int LAST_PKT_TIME_FIELD_NUMBER = 2;
    private long lastPktTime_;
    /**
     * <code>required fixed64 last_pkt_time = 2;</code>
     * @return Whether the lastPktTime field is set.
     */
    @java.lang.Override
    public boolean hasLastPktTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required fixed64 last_pkt_time = 2;</code>
     * @return The lastPktTime.
     */
    @java.lang.Override
    public long getLastPktTime() {
      return lastPktTime_;
    }

    public static final int CXID_FIELD_NUMBER = 3;
    private long cxid_;
    /**
     * <code>required fixed64 cxid = 3;</code>
     * @return Whether the cxid field is set.
     */
    @java.lang.Override
    public boolean hasCxid() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required fixed64 cxid = 3;</code>
     * @return The cxid.
     */
    @java.lang.Override
    public long getCxid() {
      return cxid_;
    }

    public static final int REVERSED_FIELD_NUMBER = 4;
    private int reversed_;
    /**
     * <code>required uint32 reversed = 4;</code>
     * @return Whether the reversed field is set.
     */
    @java.lang.Override
    public boolean hasReversed() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required uint32 reversed = 4;</code>
     * @return The reversed.
     */
    @java.lang.Override
    public int getReversed() {
      return reversed_;
    }

    public static final int AF_FIELD_NUMBER = 5;
    private int af_;
    /**
     * <code>required fixed32 af = 5;</code>
     * @return Whether the af field is set.
     */
    @java.lang.Override
    public boolean hasAf() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required fixed32 af = 5;</code>
     * @return The af.
     */
    @java.lang.Override
    public int getAf() {
      return af_;
    }

    public static final int HW_PROTO_FIELD_NUMBER = 6;
    private int hwProto_;
    /**
     * <code>required fixed32 hw_proto = 6;</code>
     * @return Whether the hwProto field is set.
     */
    @java.lang.Override
    public boolean hasHwProto() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required fixed32 hw_proto = 6;</code>
     * @return The hwProto.
     */
    @java.lang.Override
    public int getHwProto() {
      return hwProto_;
    }

    public static final int PROTO_FIELD_NUMBER = 7;
    private int proto_;
    /**
     * <code>required uint32 proto = 7;</code>
     * @return Whether the proto field is set.
     */
    @java.lang.Override
    public boolean hasProto() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required uint32 proto = 7;</code>
     * @return The proto.
     */
    @java.lang.Override
    public int getProto() {
      return proto_;
    }

    public static final int S_TOTAL_PKTS_FIELD_NUMBER = 8;
    private long sTotalPkts_;
    /**
     * <code>required fixed64 s_total_pkts = 8;</code>
     * @return Whether the sTotalPkts field is set.
     */
    @java.lang.Override
    public boolean hasSTotalPkts() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>required fixed64 s_total_pkts = 8;</code>
     * @return The sTotalPkts.
     */
    @java.lang.Override
    public long getSTotalPkts() {
      return sTotalPkts_;
    }

    public static final int S_TOTAL_BYTES_FIELD_NUMBER = 9;
    private long sTotalBytes_;
    /**
     * <code>required fixed64 s_total_bytes = 9;</code>
     * @return Whether the sTotalBytes field is set.
     */
    @java.lang.Override
    public boolean hasSTotalBytes() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>required fixed64 s_total_bytes = 9;</code>
     * @return The sTotalBytes.
     */
    @java.lang.Override
    public long getSTotalBytes() {
      return sTotalBytes_;
    }

    public static final int D_TOTAL_PKTS_FIELD_NUMBER = 10;
    private long dTotalPkts_;
    /**
     * <code>required fixed64 d_total_pkts = 10;</code>
     * @return Whether the dTotalPkts field is set.
     */
    @java.lang.Override
    public boolean hasDTotalPkts() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>required fixed64 d_total_pkts = 10;</code>
     * @return The dTotalPkts.
     */
    @java.lang.Override
    public long getDTotalPkts() {
      return dTotalPkts_;
    }

    public static final int D_TOTAL_BYTES_FIELD_NUMBER = 11;
    private long dTotalBytes_;
    /**
     * <code>required fixed64 d_total_bytes = 11;</code>
     * @return Whether the dTotalBytes field is set.
     */
    @java.lang.Override
    public boolean hasDTotalBytes() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>required fixed64 d_total_bytes = 11;</code>
     * @return The dTotalBytes.
     */
    @java.lang.Override
    public long getDTotalBytes() {
      return dTotalBytes_;
    }

    public static final int S_TCPFLAGS_FIELD_NUMBER = 12;
    private int sTcpFlags_;
    /**
     * <code>required uint32 s_tcpFlags = 12;</code>
     * @return Whether the sTcpFlags field is set.
     */
    @java.lang.Override
    public boolean hasSTcpFlags() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>required uint32 s_tcpFlags = 12;</code>
     * @return The sTcpFlags.
     */
    @java.lang.Override
    public int getSTcpFlags() {
      return sTcpFlags_;
    }

    public static final int PAD_FIELD_NUMBER = 13;
    private int pad_;
    /**
     * <code>required uint32 pad = 13;</code>
     * @return Whether the pad field is set.
     */
    @java.lang.Override
    public boolean hasPad() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>required uint32 pad = 13;</code>
     * @return The pad.
     */
    @java.lang.Override
    public int getPad() {
      return pad_;
    }

    public static final int D_TCPFLAGS_FIELD_NUMBER = 14;
    private int dTcpFlags_;
    /**
     * <code>required uint32 d_tcpFlags = 14;</code>
     * @return Whether the dTcpFlags field is set.
     */
    @java.lang.Override
    public boolean hasDTcpFlags() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>required uint32 d_tcpFlags = 14;</code>
     * @return The dTcpFlags.
     */
    @java.lang.Override
    public int getDTcpFlags() {
      return dTcpFlags_;
    }

    public static final int CHECK_FIELD_NUMBER = 15;
    private int check_;
    /**
     * <code>required uint32 check = 15;</code>
     * @return Whether the check field is set.
     */
    @java.lang.Override
    public boolean hasCheck() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>required uint32 check = 15;</code>
     * @return The check.
     */
    @java.lang.Override
    public int getCheck() {
      return check_;
    }

    public static final int HASH_FIELD_NUMBER = 16;
    private int hash_;
    /**
     * <code>required fixed32 hash = 16;</code>
     * @return Whether the hash field is set.
     */
    @java.lang.Override
    public boolean hasHash() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <code>required fixed32 hash = 16;</code>
     * @return The hash.
     */
    @java.lang.Override
    public int getHash() {
      return hash_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastPktTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCxid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReversed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAf()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHwProto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSTotalPkts()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSTotalBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDTotalPkts()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDTotalBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSTcpFlags()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPad()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDTcpFlags()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCheck()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeFixed64(1, startTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFixed64(2, lastPktTime_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFixed64(3, cxid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, reversed_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeFixed32(5, af_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeFixed32(6, hwProto_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeUInt32(7, proto_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeFixed64(8, sTotalPkts_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeFixed64(9, sTotalBytes_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeFixed64(10, dTotalPkts_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        output.writeFixed64(11, dTotalBytes_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeUInt32(12, sTcpFlags_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        output.writeUInt32(13, pad_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        output.writeUInt32(14, dTcpFlags_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        output.writeUInt32(15, check_);
      }
      if (((bitField0_ & 0x00008000) != 0)) {
        output.writeFixed32(16, hash_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, startTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, lastPktTime_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, cxid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, reversed_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(5, af_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(6, hwProto_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, proto_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(8, sTotalPkts_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(9, sTotalBytes_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(10, dTotalPkts_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(11, dTotalBytes_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, sTcpFlags_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, pad_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(14, dTcpFlags_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, check_);
      }
      if (((bitField0_ & 0x00008000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(16, hash_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ActionStateProto.ActionState)) {
        return super.equals(obj);
      }
      ActionStateProto.ActionState other = (ActionStateProto.ActionState) obj;

      if (hasStartTime() != other.hasStartTime()) return false;
      if (hasStartTime()) {
        if (getStartTime()
            != other.getStartTime()) return false;
      }
      if (hasLastPktTime() != other.hasLastPktTime()) return false;
      if (hasLastPktTime()) {
        if (getLastPktTime()
            != other.getLastPktTime()) return false;
      }
      if (hasCxid() != other.hasCxid()) return false;
      if (hasCxid()) {
        if (getCxid()
            != other.getCxid()) return false;
      }
      if (hasReversed() != other.hasReversed()) return false;
      if (hasReversed()) {
        if (getReversed()
            != other.getReversed()) return false;
      }
      if (hasAf() != other.hasAf()) return false;
      if (hasAf()) {
        if (getAf()
            != other.getAf()) return false;
      }
      if (hasHwProto() != other.hasHwProto()) return false;
      if (hasHwProto()) {
        if (getHwProto()
            != other.getHwProto()) return false;
      }
      if (hasProto() != other.hasProto()) return false;
      if (hasProto()) {
        if (getProto()
            != other.getProto()) return false;
      }
      if (hasSTotalPkts() != other.hasSTotalPkts()) return false;
      if (hasSTotalPkts()) {
        if (getSTotalPkts()
            != other.getSTotalPkts()) return false;
      }
      if (hasSTotalBytes() != other.hasSTotalBytes()) return false;
      if (hasSTotalBytes()) {
        if (getSTotalBytes()
            != other.getSTotalBytes()) return false;
      }
      if (hasDTotalPkts() != other.hasDTotalPkts()) return false;
      if (hasDTotalPkts()) {
        if (getDTotalPkts()
            != other.getDTotalPkts()) return false;
      }
      if (hasDTotalBytes() != other.hasDTotalBytes()) return false;
      if (hasDTotalBytes()) {
        if (getDTotalBytes()
            != other.getDTotalBytes()) return false;
      }
      if (hasSTcpFlags() != other.hasSTcpFlags()) return false;
      if (hasSTcpFlags()) {
        if (getSTcpFlags()
            != other.getSTcpFlags()) return false;
      }
      if (hasPad() != other.hasPad()) return false;
      if (hasPad()) {
        if (getPad()
            != other.getPad()) return false;
      }
      if (hasDTcpFlags() != other.hasDTcpFlags()) return false;
      if (hasDTcpFlags()) {
        if (getDTcpFlags()
            != other.getDTcpFlags()) return false;
      }
      if (hasCheck() != other.hasCheck()) return false;
      if (hasCheck()) {
        if (getCheck()
            != other.getCheck()) return false;
      }
      if (hasHash() != other.hasHash()) return false;
      if (hasHash()) {
        if (getHash()
            != other.getHash()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStartTime()) {
        hash = (37 * hash) + START_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStartTime());
      }
      if (hasLastPktTime()) {
        hash = (37 * hash) + LAST_PKT_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLastPktTime());
      }
      if (hasCxid()) {
        hash = (37 * hash) + CXID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCxid());
      }
      if (hasReversed()) {
        hash = (37 * hash) + REVERSED_FIELD_NUMBER;
        hash = (53 * hash) + getReversed();
      }
      if (hasAf()) {
        hash = (37 * hash) + AF_FIELD_NUMBER;
        hash = (53 * hash) + getAf();
      }
      if (hasHwProto()) {
        hash = (37 * hash) + HW_PROTO_FIELD_NUMBER;
        hash = (53 * hash) + getHwProto();
      }
      if (hasProto()) {
        hash = (37 * hash) + PROTO_FIELD_NUMBER;
        hash = (53 * hash) + getProto();
      }
      if (hasSTotalPkts()) {
        hash = (37 * hash) + S_TOTAL_PKTS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSTotalPkts());
      }
      if (hasSTotalBytes()) {
        hash = (37 * hash) + S_TOTAL_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSTotalBytes());
      }
      if (hasDTotalPkts()) {
        hash = (37 * hash) + D_TOTAL_PKTS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDTotalPkts());
      }
      if (hasDTotalBytes()) {
        hash = (37 * hash) + D_TOTAL_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDTotalBytes());
      }
      if (hasSTcpFlags()) {
        hash = (37 * hash) + S_TCPFLAGS_FIELD_NUMBER;
        hash = (53 * hash) + getSTcpFlags();
      }
      if (hasPad()) {
        hash = (37 * hash) + PAD_FIELD_NUMBER;
        hash = (53 * hash) + getPad();
      }
      if (hasDTcpFlags()) {
        hash = (37 * hash) + D_TCPFLAGS_FIELD_NUMBER;
        hash = (53 * hash) + getDTcpFlags();
      }
      if (hasCheck()) {
        hash = (37 * hash) + CHECK_FIELD_NUMBER;
        hash = (53 * hash) + getCheck();
      }
      if (hasHash()) {
        hash = (37 * hash) + HASH_FIELD_NUMBER;
        hash = (53 * hash) + getHash();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ActionStateProto.ActionState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ActionStateProto.ActionState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ActionStateProto.ActionState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ActionStateProto.ActionState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ActionStateProto.ActionState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ActionStateProto.ActionState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ActionStateProto.ActionState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ActionStateProto.ActionState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ActionStateProto.ActionState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ActionStateProto.ActionState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ActionStateProto.ActionState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ActionStateProto.ActionState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ActionStateProto.ActionState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ActionState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ActionState)
        ActionStateProto.ActionStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ActionStateProto.internal_static_ActionState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ActionStateProto.internal_static_ActionState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ActionStateProto.ActionState.class, ActionStateProto.ActionState.Builder.class);
      }

      // Construct using ActionStateProto.ActionState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        lastPktTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        cxid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        reversed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        af_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        hwProto_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        proto_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        sTotalPkts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        sTotalBytes_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        dTotalPkts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        dTotalBytes_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        sTcpFlags_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        pad_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        dTcpFlags_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        check_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        hash_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ActionStateProto.internal_static_ActionState_descriptor;
      }

      @java.lang.Override
      public ActionStateProto.ActionState getDefaultInstanceForType() {
        return ActionStateProto.ActionState.getDefaultInstance();
      }

      @java.lang.Override
      public ActionStateProto.ActionState build() {
        ActionStateProto.ActionState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ActionStateProto.ActionState buildPartial() {
        ActionStateProto.ActionState result = new ActionStateProto.ActionState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.startTime_ = startTime_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.lastPktTime_ = lastPktTime_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.cxid_ = cxid_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.reversed_ = reversed_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.af_ = af_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.hwProto_ = hwProto_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.proto_ = proto_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.sTotalPkts_ = sTotalPkts_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.sTotalBytes_ = sTotalBytes_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.dTotalPkts_ = dTotalPkts_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.dTotalBytes_ = dTotalBytes_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.sTcpFlags_ = sTcpFlags_;
          to_bitField0_ |= 0x00000800;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.pad_ = pad_;
          to_bitField0_ |= 0x00001000;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.dTcpFlags_ = dTcpFlags_;
          to_bitField0_ |= 0x00002000;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.check_ = check_;
          to_bitField0_ |= 0x00004000;
        }
        if (((from_bitField0_ & 0x00008000) != 0)) {
          result.hash_ = hash_;
          to_bitField0_ |= 0x00008000;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ActionStateProto.ActionState) {
          return mergeFrom((ActionStateProto.ActionState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ActionStateProto.ActionState other) {
        if (other == ActionStateProto.ActionState.getDefaultInstance()) return this;
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasLastPktTime()) {
          setLastPktTime(other.getLastPktTime());
        }
        if (other.hasCxid()) {
          setCxid(other.getCxid());
        }
        if (other.hasReversed()) {
          setReversed(other.getReversed());
        }
        if (other.hasAf()) {
          setAf(other.getAf());
        }
        if (other.hasHwProto()) {
          setHwProto(other.getHwProto());
        }
        if (other.hasProto()) {
          setProto(other.getProto());
        }
        if (other.hasSTotalPkts()) {
          setSTotalPkts(other.getSTotalPkts());
        }
        if (other.hasSTotalBytes()) {
          setSTotalBytes(other.getSTotalBytes());
        }
        if (other.hasDTotalPkts()) {
          setDTotalPkts(other.getDTotalPkts());
        }
        if (other.hasDTotalBytes()) {
          setDTotalBytes(other.getDTotalBytes());
        }
        if (other.hasSTcpFlags()) {
          setSTcpFlags(other.getSTcpFlags());
        }
        if (other.hasPad()) {
          setPad(other.getPad());
        }
        if (other.hasDTcpFlags()) {
          setDTcpFlags(other.getDTcpFlags());
        }
        if (other.hasCheck()) {
          setCheck(other.getCheck());
        }
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStartTime()) {
          return false;
        }
        if (!hasLastPktTime()) {
          return false;
        }
        if (!hasCxid()) {
          return false;
        }
        if (!hasReversed()) {
          return false;
        }
        if (!hasAf()) {
          return false;
        }
        if (!hasHwProto()) {
          return false;
        }
        if (!hasProto()) {
          return false;
        }
        if (!hasSTotalPkts()) {
          return false;
        }
        if (!hasSTotalBytes()) {
          return false;
        }
        if (!hasDTotalPkts()) {
          return false;
        }
        if (!hasDTotalBytes()) {
          return false;
        }
        if (!hasSTcpFlags()) {
          return false;
        }
        if (!hasPad()) {
          return false;
        }
        if (!hasDTcpFlags()) {
          return false;
        }
        if (!hasCheck()) {
          return false;
        }
        if (!hasHash()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ActionStateProto.ActionState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ActionStateProto.ActionState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long startTime_ ;
      /**
       * <code>required fixed64 start_time = 1;</code>
       * @return Whether the startTime field is set.
       */
      @java.lang.Override
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required fixed64 start_time = 1;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>required fixed64 start_time = 1;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000001;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 start_time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long lastPktTime_ ;
      /**
       * <code>required fixed64 last_pkt_time = 2;</code>
       * @return Whether the lastPktTime field is set.
       */
      @java.lang.Override
      public boolean hasLastPktTime() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required fixed64 last_pkt_time = 2;</code>
       * @return The lastPktTime.
       */
      @java.lang.Override
      public long getLastPktTime() {
        return lastPktTime_;
      }
      /**
       * <code>required fixed64 last_pkt_time = 2;</code>
       * @param value The lastPktTime to set.
       * @return This builder for chaining.
       */
      public Builder setLastPktTime(long value) {
        bitField0_ |= 0x00000002;
        lastPktTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 last_pkt_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastPktTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastPktTime_ = 0L;
        onChanged();
        return this;
      }

      private long cxid_ ;
      /**
       * <code>required fixed64 cxid = 3;</code>
       * @return Whether the cxid field is set.
       */
      @java.lang.Override
      public boolean hasCxid() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required fixed64 cxid = 3;</code>
       * @return The cxid.
       */
      @java.lang.Override
      public long getCxid() {
        return cxid_;
      }
      /**
       * <code>required fixed64 cxid = 3;</code>
       * @param value The cxid to set.
       * @return This builder for chaining.
       */
      public Builder setCxid(long value) {
        bitField0_ |= 0x00000004;
        cxid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 cxid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCxid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cxid_ = 0L;
        onChanged();
        return this;
      }

      private int reversed_ ;
      /**
       * <code>required uint32 reversed = 4;</code>
       * @return Whether the reversed field is set.
       */
      @java.lang.Override
      public boolean hasReversed() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required uint32 reversed = 4;</code>
       * @return The reversed.
       */
      @java.lang.Override
      public int getReversed() {
        return reversed_;
      }
      /**
       * <code>required uint32 reversed = 4;</code>
       * @param value The reversed to set.
       * @return This builder for chaining.
       */
      public Builder setReversed(int value) {
        bitField0_ |= 0x00000008;
        reversed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 reversed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReversed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        reversed_ = 0;
        onChanged();
        return this;
      }

      private int af_ ;
      /**
       * <code>required fixed32 af = 5;</code>
       * @return Whether the af field is set.
       */
      @java.lang.Override
      public boolean hasAf() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required fixed32 af = 5;</code>
       * @return The af.
       */
      @java.lang.Override
      public int getAf() {
        return af_;
      }
      /**
       * <code>required fixed32 af = 5;</code>
       * @param value The af to set.
       * @return This builder for chaining.
       */
      public Builder setAf(int value) {
        bitField0_ |= 0x00000010;
        af_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 af = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAf() {
        bitField0_ = (bitField0_ & ~0x00000010);
        af_ = 0;
        onChanged();
        return this;
      }

      private int hwProto_ ;
      /**
       * <code>required fixed32 hw_proto = 6;</code>
       * @return Whether the hwProto field is set.
       */
      @java.lang.Override
      public boolean hasHwProto() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required fixed32 hw_proto = 6;</code>
       * @return The hwProto.
       */
      @java.lang.Override
      public int getHwProto() {
        return hwProto_;
      }
      /**
       * <code>required fixed32 hw_proto = 6;</code>
       * @param value The hwProto to set.
       * @return This builder for chaining.
       */
      public Builder setHwProto(int value) {
        bitField0_ |= 0x00000020;
        hwProto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 hw_proto = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHwProto() {
        bitField0_ = (bitField0_ & ~0x00000020);
        hwProto_ = 0;
        onChanged();
        return this;
      }

      private int proto_ ;
      /**
       * <code>required uint32 proto = 7;</code>
       * @return Whether the proto field is set.
       */
      @java.lang.Override
      public boolean hasProto() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required uint32 proto = 7;</code>
       * @return The proto.
       */
      @java.lang.Override
      public int getProto() {
        return proto_;
      }
      /**
       * <code>required uint32 proto = 7;</code>
       * @param value The proto to set.
       * @return This builder for chaining.
       */
      public Builder setProto(int value) {
        bitField0_ |= 0x00000040;
        proto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 proto = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearProto() {
        bitField0_ = (bitField0_ & ~0x00000040);
        proto_ = 0;
        onChanged();
        return this;
      }

      private long sTotalPkts_ ;
      /**
       * <code>required fixed64 s_total_pkts = 8;</code>
       * @return Whether the sTotalPkts field is set.
       */
      @java.lang.Override
      public boolean hasSTotalPkts() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>required fixed64 s_total_pkts = 8;</code>
       * @return The sTotalPkts.
       */
      @java.lang.Override
      public long getSTotalPkts() {
        return sTotalPkts_;
      }
      /**
       * <code>required fixed64 s_total_pkts = 8;</code>
       * @param value The sTotalPkts to set.
       * @return This builder for chaining.
       */
      public Builder setSTotalPkts(long value) {
        bitField0_ |= 0x00000080;
        sTotalPkts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 s_total_pkts = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSTotalPkts() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sTotalPkts_ = 0L;
        onChanged();
        return this;
      }

      private long sTotalBytes_ ;
      /**
       * <code>required fixed64 s_total_bytes = 9;</code>
       * @return Whether the sTotalBytes field is set.
       */
      @java.lang.Override
      public boolean hasSTotalBytes() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>required fixed64 s_total_bytes = 9;</code>
       * @return The sTotalBytes.
       */
      @java.lang.Override
      public long getSTotalBytes() {
        return sTotalBytes_;
      }
      /**
       * <code>required fixed64 s_total_bytes = 9;</code>
       * @param value The sTotalBytes to set.
       * @return This builder for chaining.
       */
      public Builder setSTotalBytes(long value) {
        bitField0_ |= 0x00000100;
        sTotalBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 s_total_bytes = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSTotalBytes() {
        bitField0_ = (bitField0_ & ~0x00000100);
        sTotalBytes_ = 0L;
        onChanged();
        return this;
      }

      private long dTotalPkts_ ;
      /**
       * <code>required fixed64 d_total_pkts = 10;</code>
       * @return Whether the dTotalPkts field is set.
       */
      @java.lang.Override
      public boolean hasDTotalPkts() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>required fixed64 d_total_pkts = 10;</code>
       * @return The dTotalPkts.
       */
      @java.lang.Override
      public long getDTotalPkts() {
        return dTotalPkts_;
      }
      /**
       * <code>required fixed64 d_total_pkts = 10;</code>
       * @param value The dTotalPkts to set.
       * @return This builder for chaining.
       */
      public Builder setDTotalPkts(long value) {
        bitField0_ |= 0x00000200;
        dTotalPkts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 d_total_pkts = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearDTotalPkts() {
        bitField0_ = (bitField0_ & ~0x00000200);
        dTotalPkts_ = 0L;
        onChanged();
        return this;
      }

      private long dTotalBytes_ ;
      /**
       * <code>required fixed64 d_total_bytes = 11;</code>
       * @return Whether the dTotalBytes field is set.
       */
      @java.lang.Override
      public boolean hasDTotalBytes() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>required fixed64 d_total_bytes = 11;</code>
       * @return The dTotalBytes.
       */
      @java.lang.Override
      public long getDTotalBytes() {
        return dTotalBytes_;
      }
      /**
       * <code>required fixed64 d_total_bytes = 11;</code>
       * @param value The dTotalBytes to set.
       * @return This builder for chaining.
       */
      public Builder setDTotalBytes(long value) {
        bitField0_ |= 0x00000400;
        dTotalBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 d_total_bytes = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearDTotalBytes() {
        bitField0_ = (bitField0_ & ~0x00000400);
        dTotalBytes_ = 0L;
        onChanged();
        return this;
      }

      private int sTcpFlags_ ;
      /**
       * <code>required uint32 s_tcpFlags = 12;</code>
       * @return Whether the sTcpFlags field is set.
       */
      @java.lang.Override
      public boolean hasSTcpFlags() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>required uint32 s_tcpFlags = 12;</code>
       * @return The sTcpFlags.
       */
      @java.lang.Override
      public int getSTcpFlags() {
        return sTcpFlags_;
      }
      /**
       * <code>required uint32 s_tcpFlags = 12;</code>
       * @param value The sTcpFlags to set.
       * @return This builder for chaining.
       */
      public Builder setSTcpFlags(int value) {
        bitField0_ |= 0x00000800;
        sTcpFlags_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 s_tcpFlags = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearSTcpFlags() {
        bitField0_ = (bitField0_ & ~0x00000800);
        sTcpFlags_ = 0;
        onChanged();
        return this;
      }

      private int pad_ ;
      /**
       * <code>required uint32 pad = 13;</code>
       * @return Whether the pad field is set.
       */
      @java.lang.Override
      public boolean hasPad() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <code>required uint32 pad = 13;</code>
       * @return The pad.
       */
      @java.lang.Override
      public int getPad() {
        return pad_;
      }
      /**
       * <code>required uint32 pad = 13;</code>
       * @param value The pad to set.
       * @return This builder for chaining.
       */
      public Builder setPad(int value) {
        bitField0_ |= 0x00001000;
        pad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 pad = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearPad() {
        bitField0_ = (bitField0_ & ~0x00001000);
        pad_ = 0;
        onChanged();
        return this;
      }

      private int dTcpFlags_ ;
      /**
       * <code>required uint32 d_tcpFlags = 14;</code>
       * @return Whether the dTcpFlags field is set.
       */
      @java.lang.Override
      public boolean hasDTcpFlags() {
        return ((bitField0_ & 0x00002000) != 0);
      }
      /**
       * <code>required uint32 d_tcpFlags = 14;</code>
       * @return The dTcpFlags.
       */
      @java.lang.Override
      public int getDTcpFlags() {
        return dTcpFlags_;
      }
      /**
       * <code>required uint32 d_tcpFlags = 14;</code>
       * @param value The dTcpFlags to set.
       * @return This builder for chaining.
       */
      public Builder setDTcpFlags(int value) {
        bitField0_ |= 0x00002000;
        dTcpFlags_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 d_tcpFlags = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearDTcpFlags() {
        bitField0_ = (bitField0_ & ~0x00002000);
        dTcpFlags_ = 0;
        onChanged();
        return this;
      }

      private int check_ ;
      /**
       * <code>required uint32 check = 15;</code>
       * @return Whether the check field is set.
       */
      @java.lang.Override
      public boolean hasCheck() {
        return ((bitField0_ & 0x00004000) != 0);
      }
      /**
       * <code>required uint32 check = 15;</code>
       * @return The check.
       */
      @java.lang.Override
      public int getCheck() {
        return check_;
      }
      /**
       * <code>required uint32 check = 15;</code>
       * @param value The check to set.
       * @return This builder for chaining.
       */
      public Builder setCheck(int value) {
        bitField0_ |= 0x00004000;
        check_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 check = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearCheck() {
        bitField0_ = (bitField0_ & ~0x00004000);
        check_ = 0;
        onChanged();
        return this;
      }

      private int hash_ ;
      /**
       * <code>required fixed32 hash = 16;</code>
       * @return Whether the hash field is set.
       */
      @java.lang.Override
      public boolean hasHash() {
        return ((bitField0_ & 0x00008000) != 0);
      }
      /**
       * <code>required fixed32 hash = 16;</code>
       * @return The hash.
       */
      @java.lang.Override
      public int getHash() {
        return hash_;
      }
      /**
       * <code>required fixed32 hash = 16;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(int value) {
        bitField0_ |= 0x00008000;
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 hash = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00008000);
        hash_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ActionState)
    }

    // @@protoc_insertion_point(class_scope:ActionState)
    private static final ActionStateProto.ActionState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ActionStateProto.ActionState();
    }

    public static ActionStateProto.ActionState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ActionState>
        PARSER = new com.google.protobuf.AbstractParser<ActionState>() {
      @java.lang.Override
      public ActionState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActionState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActionState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActionState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ActionStateProto.ActionState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActionState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021actionState.proto\"\261\002\n\013ActionState\022\022\n\ns" +
      "tart_time\030\001 \002(\006\022\025\n\rlast_pkt_time\030\002 \002(\006\022\014" +
      "\n\004cxid\030\003 \002(\006\022\020\n\010reversed\030\004 \002(\r\022\n\n\002af\030\005 \002" +
      "(\007\022\020\n\010hw_proto\030\006 \002(\007\022\r\n\005proto\030\007 \002(\r\022\024\n\014s" +
      "_total_pkts\030\010 \002(\006\022\025\n\rs_total_bytes\030\t \002(\006" +
      "\022\024\n\014d_total_pkts\030\n \002(\006\022\025\n\rd_total_bytes\030" +
      "\013 \002(\006\022\022\n\ns_tcpFlags\030\014 \002(\r\022\013\n\003pad\030\r \002(\r\022\022" +
      "\n\nd_tcpFlags\030\016 \002(\r\022\r\n\005check\030\017 \002(\r\022\014\n\004has" +
      "h\030\020 \002(\007B\022B\020ActionStateProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ActionState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ActionState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActionState_descriptor,
        new java.lang.String[] { "StartTime", "LastPktTime", "Cxid", "Reversed", "Af", "HwProto", "Proto", "STotalPkts", "STotalBytes", "DTotalPkts", "DTotalBytes", "STcpFlags", "Pad", "DTcpFlags", "Check", "Hash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
